website:
  title: "MIStatlE Lab"
  description: "A high-signal growth space: math, ML theory, papers, tools, and community."
  site-url: "https://mistatle.github.io/en/"
  favicon: images/image1.png
  navbar:
    logo: images/image1.png
    left:
      - text: Home
        href: index.qmd
      - text: Guides
        menu:
          - text: Probability & Stats
            href: guides/prob/index.qmd
          - text: Optimization
            href: guides/opt/index.qmd
          - text: ML Theory
            href: guides/mlt/index.qmd
          - text: RL / Online Learning
            href: guides/rl/index.qmd
      - text: Paper Picks
        href: papers/index.qmd
      - text: Posts
        href: posts/index.qmd
      - text: Tools
        href: tools/index.qmd
      - text: Good Reads
        href: reads/index.qmd
      - text: Community
        href: community/index.qmd
      - text: About
        href: about.qmd
    right:
      - icon: github
        href: https://github.com/MIStatlE
      - icon: rss
        href: posts/index.xml
      - text: 中文
        href: ../zh/index.html

  page-footer:
    left: "© MIStatlE Lab · Built for learners"
    right: |
      Built with [Quarto](https://quarto.org) · Content CC BY 4.0

  open-graph: true
  twitter-card:
    creator: "@MIStatlE"
    card-style: summary_large_image

  sidebar:
    - id: guides
      style: "floating"
      title: "Guides"
      collapse-level: 2
      search: true
      contents:
        - text: "Overview"
          href: guides/index.qmd
        - section: "Probability & Stats"
          contents:
            - guides/prob/index.qmd
            - guides/prob/clt.qmd
            - guides/prob/concentration.qmd
        - section: "Optimization"
          contents:
            - guides/opt/index.qmd
            - guides/opt/mirror-descent.qmd
            - guides/opt/self-concordant.qmd
        - section: "ML Theory"
          contents:
            - guides/mlt/index.qmd
            - guides/mlt/generalization.qmd
        - section: "RL / Online"
          contents:
            - guides/rl/index.qmd
            - guides/rl/bandits.qmd

format:
  html:
    theme:
      light: cosmo
      dark: slate
    css: styles.css
    toc: true
    toc-depth: 3
    number-sections: false
    anchor-sections: true
    smooth-scroll: true
    code-copy: true
    code-overflow: wrap
    link-external-newwindow: true
    citations-hover: true
    html-math-method: katex
    footnotes-hover: true

collections:
  posts:
    categories: true
    feed: true
    listing:
      sort: "date desc"
      type: default
  papers:
    feed: true
    categories: true
    listing:
      type: table
      sort: "date desc"
      filter-ui: true
      fields: [title, authors, venue, year, tags]
  tools:
    feed: true
    categories: true
    listing:
      type: grid
      sort: "title"
      filter-ui: true
      image-placeholder: images/tool-card.png
  reads:
    feed: true
    listing:
      type: default
      sort: "date desc"
      filter-ui: true
  community:
    listing:
      type: default
      sort: "title"
