project:
  type: website
  output-dir: _site

website:
  title: "Alex.AI"
  description: "AI Researcher & Algorithm Engineer"
  navbar:
    background: primary # 使用这一行会自动应用下面 theme 中定义的颜色
    left:
      - text: "主页"
        href: index.qmd
      - text: "数学笔记"
        href: notes.qmd
      - text: "代码项目"
        href: projects.qmd
      - text: "关于我"
        href: about.qmd
    right:
      - icon: github
        href: https://github.com/alex-ai
      - icon: envelope
        href: mailto:alex.research@example.com

format:
  html:
    theme: 
      - cosmo
      - styles.css # 引用自定义 CSS 来微调颜色
    toc: true
    smooth-scroll: true
    highlight-style: github
