project:
  type: website
  output-dir: _site

format:
  html:
    theme:
      light: cosmo
      dark: slate
    css: styles.css
    toc: true
    toc-depth: 3
    number-sections: false
    anchor-sections: true
    smooth-scroll: true
    code-copy: true
    code-overflow: wrap
    link-external-newwindow: true
    citations-hover: true
    html-math-method: katex
    footnotes-hover: true

execute:
  freeze: auto

resources:
  - images/
  - assets/
  - index.html   # 根目录语言自动跳转页
