project:

website:
  title: "MIStatlE Lab｜密斯塔特工作室"
  description: "高信号的成长与研究空间：数学、机器学习理论、论文、工具与社区。"
  site-url: "https://mistatle.github.io/zh/"
  favicon: images/image1.png
  navbar:
    logo: images/image1.png
    left:
      - text: 首页
        href: index.zh.qmd
      - text: 指南
        menu:
          - text: 概率统计
            href: guides/prob/index.zh.qmd
          - text: 最优化
            href: guides/opt/index.zh.qmd
          - text: 机器学习理论
            href: guides/mlt/index.zh.qmd
          - text: 强化学习 / 在线学习
            href: guides/rl/index.zh.qmd
      - text: 论文精选
        href: papers/index.zh.qmd
      - text: 博文
        href: posts/index.zh.qmd
      - text: 工具
        href: tools/index.zh.qmd
      - text: 好读物
        href: reads/index.zh.qmd
      - text: 社区
        href: community/index.zh.qmd
      - text: 关于
        href: about.zh.qmd
    right:
      - icon: github
        href: https://github.com/MIStatlE
      - text: EN
        href: ../en/index.html

  page-footer:
    left: "© MIStatlE Lab · 为学习者而建"
    right: |
      由 [Quarto](https://quarto.org) 驱动 · 内容 CC BY 4.0

  open-graph: true
  twitter-card:
    creator: "@MIStatlE"
    card-style: summary_large_image

  sidebar:
    - id: guides
      style: "floating"
      title: "Guides"
      collapse-level: 2
      search: true
      contents:
        - text: "总览"
          href: guides/index.zh.qmd
        - section: "概率统计"
          contents:
            - guides/prob/index.zh.qmd
            - guides/prob/clt.zh.qmd
            - guides/prob/concentration.zh.qmd
        - section: "最优化"
          contents:
            - guides/opt/index.zh.qmd
            - guides/opt/mirror-descent.zh.qmd
            - guides/opt/self-concordant.zh.qmd
        - section: "机器学习理论"
          contents:
            - guides/mlt/index.zh.qmd
            - guides/mlt/generalization.zh.qmd
        - section: "强化学习 / 在线学习"
          contents:
            - guides/rl/index.zh.qmd
            - guides/rl/bandits.zh.qmd

format:
  html:
    theme:
      light: cosmo
      dark: slate
    css: styles.css
    toc: true
    toc-depth: 3
    number-sections: false
    anchor-sections: true
    smooth-scroll: true
    code-copy: true
    code-overflow: wrap
    link-external-newwindow: true
    citations-hover: true
    html-math-method: katex
    footnotes-hover: true

collections:
  posts:
    categories: true
    feed: true
    listing:
      sort: "date desc"
      type: default
  papers:
    feed: true
    categories: true
    listing:
      type: table
      sort: "date desc"
      filter-ui: true
      fields: [title, authors, venue, year, tags]
  tools:
    feed: true
    categories: true
    listing:
      type: grid
      sort: "title"
      filter-ui: true
      image-placeholder: images/tool-card.png
  reads:
    feed: true
    listing:
      type: default
      sort: "date desc"
      filter-ui: true
  community:
    listing:
      type: default
      sort: "title"
