# .github/workflows/quarto-publish.yml
name: Quarto Publish

on:
  push:
    branches: [ main ]   # 若默认分支是 master，这里改成 master
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        # 不要写 version: stable（会变成 vstable 404）

      # 需要执行 Jupyter/Python 再打开
      # - uses: actions/setup-python@v5
      #   with:
      #     python-version: '3.11'
      # - run: pip install jupyter

      - name: Render
        uses: quarto-dev/quarto-actions/render@v2
        with:
          path: .

      - name: Publish to GitHub Pages
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
