name: Build & Deploy Quarto (EN+ZH)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: latest

      - name: Setup Pandoc (optional but safe)
        uses: r-lib/actions/setup-pandoc@v2

      # 这行保证 _site 存在（避免任何奇怪权限/时序问题）
      - name: Ensure _site exists
        run: mkdir -p _site

      # 渲染英文站点 -> _site/en
      - name: Render EN
        run: quarto render --profile en

      # 渲染中文站点 -> _site/zh
      - name: Render ZH
        run: quarto render --profile zh

      # 上传 _site 作为 Pages 工件
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
