name: Build & Deploy Quarto (single-lang)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: 1.8.25

      - name: Clean _site
        run: rm -rf _site

      # 关键补丁：预创建常用父目录，避免 rename 目标不存在
      - name: Pre-create _site tree
        run: |
          mkdir -p _site
          for d in guides papers posts tools reads community; do
            mkdir -p "_site/$d"
          done

      - name: Render site
        run: |
          # 快速自检：确保关键页存在
          test -f index.qmd
          test -f guides/index.qmd
          # 渲染到 _site（由 _quarto.yml 的 output-dir 控制）
          quarto render --log-level=debug

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
