# .github/workflows/quarto-publish.yml
name: Quarto Publish

on:
  push:
    branches: [ main ]   # 如果默认分支是 master 改为 master
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        # 不写 version，或指定确切版本号（如 "1.6.40"）

      # 如果需要执行 Jupyter/Python 再渲染，打开下面两步
      # - uses: actions/setup-python@v5
      #   with:
      #     python-version: '3.11'
      # - run: pip install jupyter

      - name: Render site
        run: quarto render

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _site
          publish_branch: gh-pages
